CLD-257 add overwrite check
cloudinary/cloudinary_sfcc_site_cartridge pull request #16
Opened 2024-02-14 16:13 UTC by asad-rafter

2024-02-15 10:45 UTC, yuval-cloudinary requested changes
The code looks good. I don't see the metadata with the new option, can you add it

2024-02-15 12:46 UTC, asad-rafter commented
attribute is already part of metadata, so there is no need to update metadata.

2024-02-15 13:35 UTC, yuval-cloudinary commented
> attribute is already part of metadata, so there is no need to update metadata.

The request was to add a 3rd option: "CLDJobExecutionMode": Prod - backfills only
We never had "Prod - backfills only" option before

2024-02-19 10:20 UTC, yuval-cloudinary requested changes

2024-02-19 10:20 UTC, yuval-cloudinary commented on cartridges/int_cloudinary/cartridge/scripts/service/cldUpload.js
> +    if (args.executionMode && (cloudinaryConstants.PROD_BACK_FILE_EXECUTION_MODE.equals(args.executionMode))) {
for simplicity, please replace this hunk of changes with use:
 ```js
 requestObj.overwrite = true;
 if (args.executionMode && (cloudinaryConstants.PROD_BACK_FILE_EXECUTION_MODE.equals(args.executionMode))) {
        requestObj.overwrite = false;
}
```

2024-02-19 13:16 UTC, yuval-cloudinary approved these changes

2024-03-31 09:26 UTC, merged