CLD-338-rendering-PGW
cloudinary/cloudinary_sfcc_site_cartridge pull request #41
Opened 2024-12-16 14:47 UTC by asad-rafter

2024-12-17 07:53 UTC, asad-rafter commented
> @asad-rafter I'm afraid that this is not in the right direction. This uses onload, but also dynamically injects the script ensuring it will be loaded much later than needed. This slows down the loading of the PGW which causes increases in the LCP.
> 
> window.cldProductGallery is not assigned in
> 
> https://github.com/cloudinary/cloudinary_sfcc_site_cartridge/blob/018a043514adde3fba5f22362e03b741e89c975c/cartridges/cloudinary_sfra_changes/cartridge/templates/default/product/productDetails.isml#L12
> 
> Could this be the issue?

Yes, this is the issue. So the problem is, sometimes in milliseconds difference <script src="${dw.system.Site.current.preferences.custom.CLDGalleryJSURL}" /> loads late and the cloudinary object from other scripts assigned to window.cldProductGallery, in that case it breaks the PGW because the script is not available in DOM. Let me know if you have any better solution for this

2024-12-17 09:54 UTC, asad-rafter commented
> > > @asad-rafter I'm afraid that this is not in the right direction. This uses onload, but also dynamically injects the script ensuring it will be loaded much later than needed. This slows down the loading of the PGW which causes increases in the LCP.
> > > window.cldProductGallery is not assigned in
> > > https://github.com/cloudinary/cloudinary_sfcc_site_cartridge/blob/018a043514adde3fba5f22362e03b741e89c975c/cartridges/cloudinary_sfra_changes/cartridge/templates/default/product/productDetails.isml#L12
> > > 
> > > Could this be the issue?
> > 
> > 
> > Yes, this is the issue. So the problem is, sometimes in milliseconds difference <script src="${dw.system.Site.current.preferences.custom.CLDGalleryJSURL}" /> loads late and the cloudinary object from other scripts assigned to window.cldProductGallery, in that case it breaks the PGW because the script is not available in DOM. Let me know if you have any better solution for this
> 
> @asad-rafter The new code adds loading time, and still allows such a condition. Please remove the onload changes and assign window.cldProductGallery after
> 
> https://github.com/cloudinary/cloudinary_sfcc_site_cartridge/blob/018a043514adde3fba5f22362e03b741e89c975c/cartridges/cloudinary_sfra_changes/cartridge/templates/default/product/productDetails.isml#L12
> 
> exactly like it is done in all other places you call the widget

PGW is only called on PDP, where we are using the onload

2025-01-07 11:47 UTC, yuval-cloudinary commented
> PGW is only called on PDP, where we are using the onload. let's suppose we have added <script src="${dw.system.Site.current.preferences.custom.CLDGalleryJSURL}" /> in isml template, then how would we know its loaded and now assign it and how can we assign cloudinary to window.cldProductGallery in isml

@asad-rafter You'll add a script tag immediately following the above script tag, so it will look like this:
```javascript
<script src="${dw.system.Site.current.preferences.custom.CLDGalleryJSURL}" />
<script>
window.cldProductGallery = cloudinary;
</script>
```

2025-01-07 12:18 UTC, asad-rafter commented
> > PGW is only called on PDP, where we are using the onload. let's suppose we have added <script src="${dw.system.Site.current.preferences.custom.CLDGalleryJSURL}" /> in isml template, then how would we know its loaded and now assign it and how can we assign cloudinary to window.cldProductGallery in isml
> 
> @asad-rafter You'll add a script tag immediately following the above script tag, so it will look like this:
> 
> ```js
> <script src="${dw.system.Site.current.preferences.custom.CLDGalleryJSURL}" />
> <script>
> window.cldProductGallery = cloudinary;
> </script>
> ```

@yuval-cloudinary We were already using this and it was causing issue, that's why we change it on onload

2025-01-07 12:32 UTC, yuval-cloudinary commented
> > > PGW is only called on PDP, where we are using the onload. let's suppose we have added <script src="${dw.system.Site.current.preferences.custom.CLDGalleryJSURL}" /> in isml template, then how would we know its loaded and now assign it and how can we assign cloudinary to window.cldProductGallery in isml
> > 
> > 
> > @asad-rafter You'll add a script tag immediately following the above script tag, so it will look like this:
> > ```js
> > <script src="${dw.system.Site.current.preferences.custom.CLDGalleryJSURL}" />
> > <script>
> > window.cldProductGallery = cloudinary;
> > </script>
> > ```
> 
> @yuval-cloudinary We were already using this and it was causing issue, that's why we change it on onload

2025-01-07 12:33 UTC, yuval-cloudinary commented
@asad-rafter I don't think we had this way. Can you share a link to the previous time?

2025-01-07 12:36 UTC, asad-rafter commented
> @asad-rafter I don't think we had this way. Can you share a link to the previous time?

https://github.com/cloudinary/cloudinary_sfcc_site_cartridge/blob/018a043514adde3fba5f22362e03b741e89c975c/cartridges/cloudinary_sfra_changes/cartridge/templates/default/product/bundleDetails.isml#L13

2025-01-07 12:59 UTC, yuval-cloudinary commented
> https://github.com/cloudinary/cloudinary_sfcc_site_cartridge/blob/018a043514adde3fba5f22362e03b741e89c975c/cartridges/cloudinary_sfra_changes/cartridge/templates/default/product/bundleDetails.isml#L13

Having this syntax is equivalent, do I don't mind it:
```javascript
<script src="${dw.system.Site.current.preferences.custom.CLDGalleryJSURL}" onload="window.cldProductGallery = cloudinary;" />
```

As long as this snippet is part of the rendered HTML and is not injected after the page load

2025-01-14 09:35 UTC, asad-rafter commented
@yuval-cloudinary the requested changes has been updated

2025-01-14 12:31 UTC, yuval-cloudinary requested changes

2025-01-14 12:31 UTC, yuval-cloudinary commented on cartridges/cloudinary_sfra_changes/cartridge/templates/default/product/bundleDetails.isml
> +        <script src="${dw.system.Site.current.preferences.custom.CLDGalleryJSURL}" onload="window.cldProductGallery = cloudinary; window.renderCloudinaryGalleryWidget();"> </script>
@asad-rafter this call to window.renderCloudinaryGalleryWidget() is (possibly) executed  before we have the div "cld-gallery" in the DOM. 
Are we able to inject it after the "<div id="cld-gallery"></div>" and "<div id="cld-gallery-..."></div>?

If so, then we would be able to remove the additional call to the function after the document is ready:
https://github.com/asad-rafter/cloudinary_sfcc_site_cartridge/blob/9ab65cc0dbeaa7e3ec12e9e4a1fc869096563d6d/cartridges/int_cloudinary/cartridge/js/cloudinaryWidgets.js#L5

2025-01-15 09:06 UTC, asad-rafter commented on cartridges/cloudinary_sfra_changes/cartridge/templates/default/product/bundleDetails.isml
> +        <script src="${dw.system.Site.current.preferences.custom.CLDGalleryJSURL}" onload="window.cldProductGallery = cloudinary; window.renderCloudinaryGalleryWidget();"> </script>
@yuval-cloudinary do you want to remove `window.renderCloudinaryGalleryWidget();` from script tag?

2025-01-15 09:14 UTC, yuval-cloudinary commented on cartridges/cloudinary_sfra_changes/cartridge/templates/default/product/bundleDetails.isml
> +        <script src="${dw.system.Site.current.preferences.custom.CLDGalleryJSURL}" onload="window.cldProductGallery = cloudinary; window.renderCloudinaryGalleryWidget();"> </script>
@asad-rafter I like the window.renderCloudinaryGalleryWidget(); in the script tag, it just needs to be added lower at the rendered HTML

2025-01-15 09:35 UTC, asad-rafter commented on cartridges/cloudinary_sfra_changes/cartridge/templates/default/product/bundleDetails.isml
> +        <script src="${dw.system.Site.current.preferences.custom.CLDGalleryJSURL}" onload="window.cldProductGallery = cloudinary; window.renderCloudinaryGalleryWidget();"> </script>
@yuval-cloudinary changes have been made and deployed on 007

2025-01-19 11:38 UTC, yuval-cloudinary requested changes

2025-01-19 11:38 UTC, yuval-cloudinary commented on cartridges/cloudinary_sfra_changes/cartridge/templates/default/product/bundleDetails.isml
> +                <script src="${dw.system.Site.current.preferences.custom.CLDGalleryJSURL}" onload="window.cldProductGallery = cloudinary; window.renderCloudinaryGalleryWidget();"> </script>
Please remove the legacy calls to renderCloudinaryGalleryWidget from https://github.com/asad-rafter/cloudinary_sfcc_site_cartridge/blob/984285740779e611bacfdcb5f6cc623a559ff505/cartridges/int_cloudinary/cartridge/js/cloudinaryWidgets.js#L93

2025-01-19 11:38 UTC, yuval-cloudinary commented on cartridges/cloudinary_sfra_changes/cartridge/templates/default/product/setDetails.isml
> +            <script src="${dw.system.Site.current.preferences.custom.CLDGalleryJSURL}" onload="window.cldProductGallery = cloudinary; window.renderCloudinarySetGalleryWidgets();"></script>
Please remove the legacy calls to renderCloudinarySetGalleryWidget from https://github.com/asad-rafter/cloudinary_sfcc_site_cartridge/blob/984285740779e611bacfdcb5f6cc623a559ff505/cartridges/int_cloudinary/cartridge/js/cloudinaryWidgets.js#L95

2025-01-21 08:50 UTC, asad-rafter commented on cartridges/cloudinary_sfra_changes/cartridge/templates/default/product/bundleDetails.isml
> +                <script src="${dw.system.Site.current.preferences.custom.CLDGalleryJSURL}" onload="window.cldProductGallery = cloudinary; window.renderCloudinaryGalleryWidget();"> </script>
@yuval-cloudinary made the changes

2025-01-29 14:10 UTC, merged