CLD-253
cloudinary/cloudinary_sfcc_site_cartridge pull request #6
Opened 2023-11-10 10:19 UTC by asad-rafter

2023-12-06 07:25 UTC, yuval-cloudinary requested changes
The PR has only metadata changes. The actual code is missing

2023-12-06 08:57 UTC, asad-rafter commented
@yuval-cloudinary I don't think this PR has any code changes, there were only metadata changes

2023-12-06 10:11 UTC, yuval-cloudinary commented
@asad-rafter  - this PR includes new metadata with "Step used to create necessary structured metadata in the Cloudinary". This step doesn't have the code related to it. This step shouldn't be here, as it belongs to a different JIRA

2023-12-06 10:12 UTC, yuval-cloudinary requested changes

2023-12-10 09:48 UTC, yuval-cloudinary approved these changes

2023-12-17 16:41 UTC, merged