updated version
cloudinary/cloudinary_sfcc_site_cartridge pull request #8
Opened 2023-12-07 08:07 UTC by asad-rafter

2023-12-10 10:00 UTC, yuval-cloudinary requested changes

2023-12-10 10:00 UTC, yuval-cloudinary commented on metadata/cloudinary-metadata.zip
There is a version.txt file saying 20.1.3. If this is the cartridge version it should be bumped as well

2023-12-11 07:29 UTC, asad-rafter commented on metadata/cloudinary-metadata.zip
I have updated the file with cartridge version.

2023-12-11 08:29 UTC, yuval-cloudinary approved these changes

2023-12-17 16:49 UTC, merged